/** barrel for screen */
export * from './home/Home';
export * from './user/register/Identify';
export * from './user/login/Login';
export * from './user/User';
export * from './user/agree-info/AgreeInfo';
export * from './user/identification/Identification';
export * from './common/privacy/Privacy';
export * from './common/collect/Collect';
export * from './common/terms/Terms';
export * from './customer/faq/Faq';
export * from './user/edit/Edit';
export * from './user/withdrawal/Withdrawal';
export * from './user/add-nick/AddNick';
export * from './user/register/input-id/InputId';
export * from './user/register/input-pwd/InputPwd';
export * from './user/register/input-gender/InputGender';
export * from './home/intro/Intro';
export * from './customer/Customer';
export * from './event/Event';
export * from './market/Market';
export * from './market/cart/Cart';
export * from './market/detail/Detail';
export * from './contents/Contents';
export * from './setting/Setting';
export * from './user/report/Report';
export * from './user/result-id/ResultId';
export * from './user/coupon/Coupon';
export * from './user/point/Point';
export * from './user/review/Review';
export * from './contents/mbti/Mbti';
export * from './setting/alarm/SettingAlarm';
export * from './customer/notice/Notice';
export * from './customer/inquiry/Inquiry';
export * from './setting/profile/SettingProfile';
export * from './setting/terms-setting/SettingTerms';
export * from './home/banner/Banner';
export * from './home/latest-mbti/LatestMbti';
export * from './home/latest-game/LatestGame';
export * from './home/candy/Candy';
export * from './home/latest-coupon/LatestCoupon';
export * from './home/goods-item/GoodsItem';
export * from './home/family-site/FamilySite';
export * from './contents/game/Game';
export * from './contents/best/Best';
export * from './contents/view/ViewMbti';
export * from './contents/view/ViewGame';

export * from './contents/recommend/Recommend';
export * from './contents/mbti/survey/Survey';
export * from './contents/mbti/result/Result';
export * from './home/footer/Footer';
export * from './user/mypage/like/Like';
export * from './user/mypage/like/like-test-items/LikeTestItems';
export * from './user/mypage/rcmnd-code/RcmndCode';
export * from './user/mypage/review-management/ReviewList';
export * from './user/mypage/review-management/WriteReview';
export * from './user/mypage/Mypage';
export * from './user/mypage/dna-progress/DnaProgress';
export * from './user/mypage/recent-candy/RecentCandy';
export * from './user/mypage/recent-play/RecentPlay';
export * from './user/mypage/like/like-dna-items/LikeDnaItems';
export * from './user/mypage/order-history/OrderHistory';
export * from './user/mypage/order-history/order-history-detail/order-history-items/OrderHistoryItems';
export * from './user/mypage/review-management/review-list-items/ReviewItem';
export * from './user/mypage/review-management/review-list-items/PossibleReviewItem';
export * from './user/mypage/review-management/UploadReviewImage';
export * from './market/market-payment/MarketPayment';
export * from './market/order/OrderResult';
export * from './market/cart/coupon-dialog/CouponDialog';
export * from './user/point/point-list/SavedPointHistory';
export * from './market/market-payment/address/Address';
export * from './market/market-payment/address/address-list/AddressList';
export * from './market/market-payment/address/add/Add';
export * from './user/mypage/mycard/Mycard';
export * from './home/content-item/ContentItem';
export * from './home/sub-banner/SubBanner';
export * from './user/mypage/mycard/Mycard';
export * from './home/content-item/ContentItem';
export * from './contents/onepick/onepick-splash/OnepickSplash';
export * from './contents/onepick/onepick-result/OnepickResult';
export * from './contents/onepick/onepick-splash/OnepickSplash';
export * from './contents/onepick/onepick-result/OnepickResult';
export * from './user/mypage/dna-result/DnaResult';
export * from './user/mypage/dna-result/DnaCard';
export * from './user/mypage/dna-result/dna-result-detail/detail-card/DnaCardPopular';
export * from './user/mypage/dna-result/dna-result-detail/DnaResultDetail';
export * from './user/mypage/dna-result/dna-result-detail/LifeTips';
export * from './user/mypage/search-dna-card/SearchDnaCard';
export * from './user/mypage/search-dna-card/dna-card-list/DnaCardList';
export * from './user/mypage/dna-result/DnaList';
export * from './user/mypage/order-history/order-history-detail/FirstOrderHistoryDetail';
export * from './user/mypage/order-history/order-history-detail/order-history-items/PaymentInfoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/first/FirstOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/DeliveryInfoItems';
export * from './user/mypage/exchange-alert/ExchangeAlert';
export * from './user/mypage/dna-result/DnaResult';
export * from './user/mypage/dna-result/dna-result-detail/detail-card/DnaDetailCard';
export * from './user/mypage/mbti-card/MbtiCard';
export * from './user/mypage/order-history/order-history-buttons/OrderHistoryDetailButtons';
export * from './user/mypage/order-history/order-history-detail/AdditionlOrderHistoryDetail';
export * from './user/mypage/order-history/order-history-detail/order-history-items/additional/AdditionalOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/ready/ReadyOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/ShippingKitOrderHistoryDetail';
export * from './user/mypage/order-history/order-history-detail/order-history-items/shipping-kit/ShippingKitOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/delivered-kit/DeliveredKitOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/exchange/ExchangingOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/refund/RefundOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/return-request-kit/ReturnRequestKitOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/ArrivedKitOrderHistoryDetail';
export * from './user/mypage/order-history/order-history-detail/order-history-items/arrived-kit/ArrivedKitOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/MakingCandyOrderHistoryDetail';
export * from './user/mypage/order-history/order-history-detail/order-history-items/making-candy/MakingCandyOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/made-candy/MadeCandyOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/MadeCandyOrderHistoryDetail';
export * from './user/mypage/order-history/OrderHistoryDetail';
export * from './user/mypage/order-history/order-history-items/order-items/multiple-purchase-items/MultiplePurchaseItems';
export * from './user/mypage/order-history/order-history-items/order-items/single-purchase-items/SinglePurchaseItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/cancel/CancelingOrderNoItems';
export * from './user/mypage/order-history/order-history-detail/order-history-items/cancel/CanceledOrderNoItems';
export * from './user/mypage/review-dialog/ReviewDialog';
export * from './user/mypage/order-history/order-history-detail/delivery-tracking/DeliveryTracking';
export * from './user/mypage/order-history/order-history-detail/delivery-tracking/delivery-faq/DeliveryFaq';
export * from './user/mypage/order-history/order-history-detail/delivery-tracking/delivery-items/DeliveryItems';
export * from './user/mypage/order-history/order-history-detail/delivery-tracking/delivery-status/DeliveryStatus';
export * from './user/mypage/dna-result-dialog/DnaResultDialog';
export * from './user/mypage/order-history/order-history-detail/order-cancel/OrderCancel';
export * from './user/mypage/order-history/order-history-detail/order-cancel/OrderCancelResult';
export * from "./user/mypage/order-history/kit-return-request/KitReturnRequest"
export * from "./user/mypage/order-history/kit-return-result/KitReturnResult"
export * from "./contents/onepick/onepick-splash/blower/Blower"
export * from "./user/mypage/order-history/order-history-timeline/OrderHistoryTimeline"
export * from "./user/mypage/order-history/order-history-items/order-items/multiple-purchase-items/open-status-items/OpenStatusItems"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/GenoData"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/DnaCardNotice"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/dna-card-notice/TestMeaningList"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/dna-card-notice/GenoPrivacyActList"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/dna-card-notice/CautionList"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/dna-card-notice/ReferenceList"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/DnaCardChart"
export * from "./user/mypage/order-history/order-history-detail/DefaultOrderHistoryDetail"
export * from "./user/mypage/order-history/order-history-detail/order-history-items/default-order-no-items/DefaultOrderNoItems"
export * from "./common/token-check/TokenCheck"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/DnaCardSurvey"
export * from "./user/mypage/dna-result/dna-result-detail/detail-card/dna-card-survey/QuestionItems"
export * from './customer/inquiry/inquiry-order-history/InquiryOrderHistory';
export * from "./user/mypage/analysis-guide/AnalysisGuide"
export * from "./user/mypage/analysis-guide/analysis-guide-items/ReportCode"
export * from "./user/mypage/analysis-guide/analysis-guide-items/QCResultInfo"
export * from "./user/mypage/analysis-guide/analysis-guide-items/LabInfo"
export * from "./user/mypage/analysis-guide/analysis-guide-items/ResponsiblePerson"
export * from "./user/mypage/analysis-guide/analysis-guide-items/AnalysisGuideFooter"
// export * from './user/mypage/dna-result/dna-result-detail/detail-card/dna-card-survey/answer-items/AnswerItems';
export * from './contents/share/Share';
export * from "./customer/customerMain/CustomerNotice"
export * from "./main/Main"

export * from "./main/banner-main/BannerMain"
export * from "./main/why-this-app/WhyThisApp"
export * from "./main/test-result/TestResult"
export * from "./main/recommend-md/RecommendMd"
export * from "./main/collect-result-card/CollectResultCard"
export * from "./event/fcfs/Fcfs"
export * from "./event/scratch/Scratch"
export * from "./event/prize/Prize"
export * from "./main/main-sub-banner/MainSubBanner"
export * from "./common/install-popup/InstallPopup"
